#log setup
log:
  #can set output to file, others will be outputed to std
  output: std
  name: log.txt
  #level can be: all, debug, info,, warn, error, fatal
  level: all
  enable_line: true

http:
  addr: :52001
  profile: true
  mode: debug

nsqd:
  addr: 127.0.0.1:4150
