#log setup
log:
  #can set output to file, others will be outputed to std
  output: std
  name: log.txt
  #level can be: all, debug, info,, warn, error, fatal
  level: all
  enable_line: true

service:
  externalip: true
  rpc:
    port: ":50002"
  tcp:
    port: ":51001"
